<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import { ArrowLeft, Check } from 'lucide-vue-next';
import AppLayout from '../../Layouts/AppLayout.vue';

defineOptions({ layout: AppLayout });
const props = defineProps({ cheques: Array, accounts: Array, contacts: Array, summary: Object });
const form = useForm({ bank_account_id: props.accounts?.[0]?.id || '', contact_id: '', cheque_no: '', cheque_date: new Date().toISOString().slice(0, 10), amount: '', direction: 'In', status: 'Pending', notes: '' });
const submit = () => form.post('/cheques', { onSuccess: () => form.reset('cheque_no', 'amount', 'notes') });
</script>
<template>
    <Head title="Cheques" />
    <div class="page-heading"><div><p class="eyebrow"><span class="dot" /> Treasury control</p><h1>Cheques with a clear next step.</h1><p>Record incoming and outgoing instruments before they become reconciliation surprises.</p></div><Link href="/banking" class="btn btn-ghost"><ArrowLeft :size="15" /> Banking</Link></div>
    <div class="metric-strip"><div class="mini-metric"><span>Pending</span><strong>{{ summary.pending }}</strong><em>Awaiting clearance</em></div><div class="mini-metric"><span>Incoming</span><strong>{{ summary.in }}</strong><em>Recorded instruments</em></div><div class="mini-metric"><span>Outgoing</span><strong>{{ summary.out }}</strong><em>Recorded instruments</em></div></div>
    <div class="dashboard-grid"><section class="card"><div class="card-header"><div><h2>Cheque register</h2><p>Incoming and outgoing instruments</p></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Cheque</th><th>Account</th><th>Contact</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr v-for="cheque in cheques" :key="cheque.number"><td><div class="data-title">{{ cheque.number }}</div><div class="data-subtitle">{{ cheque.direction === 'In' ? 'Incoming' : 'Outgoing' }}</div></td><td>{{ cheque.bank }}</td><td>{{ cheque.contact }}</td><td>{{ cheque.date }}</td><td><strong>{{ cheque.amount }}</strong></td><td><span class="status-pill" :class="{ warning: cheque.status === 'Pending', danger: cheque.status === 'Bounced' }">{{ cheque.status }}</span></td></tr></tbody></table></div></section><section class="card form-card"><div class="card-header" style="padding:0 0 18px"><div><h2>Record cheque</h2><p>Clear it later when your bank confirms.</p></div></div><form class="form-grid" @submit.prevent="submit"><div class="field"><label>Bank account</label><select v-model="form.bank_account_id"><option v-for="account in accounts" :key="account.id" :value="account.id">{{ account.name }}</option></select></div><div class="field"><label>Contact</label><select v-model="form.contact_id"><option value="">Internal / walk-in</option><option v-for="contact in contacts" :key="contact.id" :value="contact.id">{{ contact.name }}</option></select></div><div class="field"><label>Cheque number</label><input v-model="form.cheque_no" placeholder="CHQ-2403" /></div><div class="field"><label>Date</label><input v-model="form.cheque_date" type="date" /></div><div class="field"><label>Amount</label><input v-model="form.amount" type="number" min="1" step="0.01" placeholder="0" /></div><div class="field"><label>Direction</label><select v-model="form.direction"><option>In</option><option>Out</option></select></div><div class="field"><label>Status</label><select v-model="form.status"><option>Pending</option><option>Cleared</option><option>Bounced</option></select></div><div class="field"><label>Notes</label><input v-model="form.notes" placeholder="Against invoice" /></div><div class="form-actions full"><button class="btn btn-primary" type="submit" :disabled="form.processing"><Check :size="15" /> Record cheque</button></div></form></section></div>
</template>
