<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\OperationsController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\WorkspaceController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PublicController::class, 'home'])->name('home');
Route::get('/register/{step?}', [PublicController::class, 'register'])->name('register');
Route::post('/register', [PublicController::class, 'storeRegistration'])->name('register.store');
Route::middleware('guest')->group(function () {
    Route::get('/admin/login', [AuthController::class, 'create'])->name('login');
    Route::post('/admin/login', [AuthController::class, 'store'])->name('login.store');
});

Route::middleware('auth')->group(function () {
    Route::post('/admin/logout', [AuthController::class, 'destroy'])->name('logout');
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory.index');
    Route::get('/inventory/create', [InventoryController::class, 'create'])->name('inventory.create');
    Route::post('/inventory', [InventoryController::class, 'store'])->name('inventory.store');
    Route::get('/inventory/variants', [InventoryController::class, 'variants'])->name('inventory.variants');
    Route::get('/inventory/variants/create', [InventoryController::class, 'createVariant'])->name('inventory.variants.create');
    Route::post('/inventory/variants', [InventoryController::class, 'storeVariant'])->name('inventory.variants.store');
    Route::get('/inventory/labels', [InventoryController::class, 'labels'])->name('inventory.labels');
    Route::post('/inventory/bulk-update', [InventoryController::class, 'bulkUpdate'])->name('inventory.bulk-update');
    Route::get('/inventory/{product}', [InventoryController::class, 'show'])->name('inventory.show');
    Route::get('/inventory/{product}/edit', [InventoryController::class, 'edit'])->name('inventory.edit');
    Route::patch('/inventory/{product}', [InventoryController::class, 'update'])->name('inventory.update');
    Route::delete('/inventory/{product}', [InventoryController::class, 'destroy'])->name('inventory.destroy');
    Route::get('/pos', [WorkspaceController::class, 'pos'])->name('pos.index');
    Route::post('/pos', [WorkspaceController::class, 'storePos'])->name('pos.store');
    Route::get('/sales', [WorkspaceController::class, 'sales'])->name('sales.index');
    Route::get('/sales/create', [WorkspaceController::class, 'createSale'])->name('sales.create');
    Route::post('/sales', [WorkspaceController::class, 'storeSale'])->name('sales.store');
    Route::get('/purchase', [WorkspaceController::class, 'purchases'])->name('purchases.index');
    Route::get('/purchase/create', [WorkspaceController::class, 'createPurchase'])->name('purchases.create');
    Route::post('/purchase', [WorkspaceController::class, 'storePurchase'])->name('purchases.store');
    Route::get('/account', [WorkspaceController::class, 'accounting'])->name('accounting.index');
    Route::get('/account/ledger', [WorkspaceController::class, 'ledger'])->name('ledger.index');
    Route::get('/account/ledger/create', [WorkspaceController::class, 'createLedger'])->name('ledger.create');
    Route::post('/account/ledger', [WorkspaceController::class, 'storeLedger'])->name('ledger.store');
    Route::get('/invoices', [WorkspaceController::class, 'invoices'])->name('invoices.index');
    Route::get('/payments', [WorkspaceController::class, 'payments'])->name('payments.index');
    Route::get('/payments/create', [WorkspaceController::class, 'createPayment'])->name('payments.create');
    Route::post('/payments', [WorkspaceController::class, 'storePayment'])->name('payments.store');
    Route::get('/returns', [WorkspaceController::class, 'returns'])->name('returns.index');
    Route::get('/returns/create', [WorkspaceController::class, 'createReturn'])->name('returns.create');
    Route::post('/returns', [WorkspaceController::class, 'storeReturn'])->name('returns.store');
    Route::get('/transfers', [WorkspaceController::class, 'transfers'])->name('transfers.index');
    Route::get('/transfers/create', [WorkspaceController::class, 'createTransfer'])->name('transfers.create');
    Route::post('/transfers', [WorkspaceController::class, 'storeTransfer'])->name('transfers.store');
    Route::post('/transfers/{transfer}/receive', [WorkspaceController::class, 'receiveTransfer'])->name('transfers.receive');
    Route::get('/branches', [WorkspaceController::class, 'branches'])->name('branches.index');
    Route::get('/branches/create', [WorkspaceController::class, 'createBranch'])->name('branches.create');
    Route::post('/branches', [WorkspaceController::class, 'storeBranch'])->name('branches.store');
    Route::get('/employees', [WorkspaceController::class, 'employees'])->name('employees.index');
    Route::get('/employees/create', [WorkspaceController::class, 'createEmployee'])->name('employees.create');
    Route::post('/employees', [WorkspaceController::class, 'storeEmployee'])->name('employees.store');
    Route::get('/warehouses', [WorkspaceController::class, 'warehouses'])->name('warehouses.index');
    Route::get('/warehouses/create', [WorkspaceController::class, 'createWarehouse'])->name('warehouses.create');
    Route::post('/warehouses', [WorkspaceController::class, 'storeWarehouse'])->name('warehouses.store');
    Route::get('/contacts', [WorkspaceController::class, 'contacts'])->name('contacts.index');
    Route::get('/contacts/create', [WorkspaceController::class, 'createContact'])->name('contacts.create');
    Route::post('/contacts', [WorkspaceController::class, 'storeContact'])->name('contacts.store');
    Route::get('/reports', [WorkspaceController::class, 'reports'])->name('reports.index');
    Route::get('/settings', [WorkspaceController::class, 'settings'])->name('settings.index');
    Route::get('/settings/access', [OperationsController::class, 'access'])->middleware('role:Administrator')->name('access.index');
    Route::post('/settings/access', [OperationsController::class, 'storeAccess'])->middleware('role:Administrator')->name('access.store');
    Route::get('/banking', [OperationsController::class, 'banking'])->name('banking.index');
    Route::post('/banking', [OperationsController::class, 'storeBankAccount'])->name('banking.store');
    Route::get('/cheques', [OperationsController::class, 'cheques'])->name('cheques.index');
    Route::post('/cheques', [OperationsController::class, 'storeCheque'])->name('cheques.store');
    Route::get('/cost-centres', [OperationsController::class, 'costCenters'])->name('cost-centers.index');
    Route::post('/cost-centres', [OperationsController::class, 'storeCostCenter'])->name('cost-centers.store');
    Route::get('/production', [OperationsController::class, 'production'])->name('production.index');
    Route::get('/production/create', [OperationsController::class, 'createProduction'])->name('production.create');
    Route::post('/production', [OperationsController::class, 'storeProduction'])->name('production.store');
    Route::post('/production/{order}/complete', [OperationsController::class, 'completeProduction'])->name('production.complete');
});
