<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import { ArrowLeft, ArrowRight, Check, Sparkles } from 'lucide-vue-next';

const props = defineProps({ step: String });
const form = useForm({ name: '', email: '', phone: '', business_name: '', business_type: 'Retail', branch_count: 1 });
const submit = () => form.post('/register');
</script>

<template>
    <Head title="Start a workspace" />
    <main class="public-register"><div class="register-top"><Link href="/" class="public-brand"><span class="brand-mark"><Sparkles :size="18" /></span><strong>redbook<span>one</span></strong></Link><Link href="/admin/login" class="btn btn-ghost">Already have access</Link></div><section v-if="props.step === 'complete'" class="register-card complete-card"><div class="auth-lock"><Check :size="18" /></div><p class="eyebrow"><span class="dot" /> Request received</p><h1>Your workspace is on its way.</h1><p>We have the details we need to prepare your Redbook demo workspace. A team member can follow up with next steps.</p><Link href="/" class="btn btn-primary">Back to Redbook one <ArrowRight :size="15" /></Link></section><section v-else class="register-card"><div class="register-progress"><span :class="{ active: props.step === 'business' }">01 Business</span><span :class="{ active: props.step === 'team' }">02 Your team</span><span :class="{ active: props.step === 'branch' }">03 Branches</span></div><p class="eyebrow"><span class="dot" /> Build a calmer workspace</p><h1>Tell us where the work lives.</h1><p>Start with a few details. You can refine the system after the demo workspace is ready.</p><form class="register-form" @submit.prevent="submit"><div class="field"><label for="name">Your name</label><input id="name" v-model="form.name" placeholder="Amina Rahman" /><small v-if="form.errors.name" class="form-error">{{ form.errors.name }}</small></div><div class="field"><label for="email">Work email</label><input id="email" v-model="form.email" type="email" placeholder="you@company.com" /><small v-if="form.errors.email" class="form-error">{{ form.errors.email }}</small></div><div class="field"><label for="business_name">Business name</label><input id="business_name" v-model="form.business_name" placeholder="Redbook Holdings" /><small v-if="form.errors.business_name" class="form-error">{{ form.errors.business_name }}</small></div><div class="field"><label for="business_type">Business type</label><select id="business_type" v-model="form.business_type"><option>Retail</option><option>Wholesale</option><option>Distribution</option><option>Manufacturing</option><option>Services</option></select></div><div class="field"><label for="phone">Phone <span class="field-hint">optional</span></label><input id="phone" v-model="form.phone" placeholder="+880 1700 000 000" /></div><div class="field"><label for="branch_count">Branches or locations</label><input id="branch_count" v-model="form.branch_count" type="number" min="1" max="500" /><small v-if="form.errors.branch_count" class="form-error">{{ form.errors.branch_count }}</small></div><div class="form-actions"><Link href="/" class="btn btn-ghost"><ArrowLeft :size="15" /> Back</Link><button class="btn btn-primary" type="submit" :disabled="form.processing">{{ form.processing ? 'Sending…' : 'Request workspace' }} <ArrowRight :size="15" /></button></div></form></section></main>
</template>
