<script setup>
import { Head, Link, router } from '@inertiajs/vue3';
import { ArrowLeft, Edit3, Trash2 } from 'lucide-vue-next';
import AppLayout from '../../Layouts/AppLayout.vue';

defineOptions({ layout: AppLayout });
defineProps({ product: Object, variants: Array, branchStocks: Array });
const archive = (id) => { if (window.confirm('Archive this product from active inventory?')) router.delete(`/inventory/${id}`); };
</script>
<template>
    <Head :title="product.name" />
    <div class="page-heading"><div><p class="eyebrow"><span class="dot" /> Product detail</p><h1>{{ product.name }}</h1><p>{{ product.description || 'A complete product record with branch stock, variants and pricing context.' }}</p></div><div class="heading-actions"><Link href="/inventory" class="btn btn-ghost"><ArrowLeft :size="15" /> Inventory</Link><Link :href="`/inventory/${product.id}/edit`" class="btn btn-primary"><Edit3 :size="15" /> Edit product</Link></div></div>
    <div class="metric-strip"><div class="mini-metric"><span>Available stock</span><strong>{{ product.stock }}</strong><em>Reorder at {{ product.reorderLevel }}</em></div><div class="mini-metric"><span>Retail price</span><strong>৳ {{ product.price.toLocaleString() }}</strong><em>{{ product.priceLabel || 'Standard price' }}</em></div><div class="mini-metric"><span>Variants</span><strong>{{ variants.length }}</strong><em>Sellable options</em></div><div class="mini-metric"><span>Barcode</span><strong>{{ product.barcode || '—' }}</strong><em>{{ product.sku }}</em></div></div>
    <div class="dashboard-grid"><section class="card"><div class="card-header"><div><h2>Branch stock</h2><p>{{ product.brand || 'Unbranded' }} · {{ product.category }} · sold by {{ product.unit }}</p></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Branch</th><th>Allocated quantity</th><th>Share</th></tr></thead><tbody><tr v-for="stock in branchStocks" :key="stock.branch"><td class="data-title">{{ stock.branch }}</td><td>{{ stock.quantity }}</td><td>{{ product.stock ? Math.round(stock.quantity / product.stock * 100) : 0 }}%</td></tr></tbody></table></div></section><section class="card"><div class="card-header"><div><h2>Commercial context</h2><p>Prices used by different workflows</p></div></div><div class="activity-list"><div class="detail-row"><span>Cost price</span><strong>৳ {{ product.costPrice.toLocaleString() }}</strong></div><div class="detail-row"><span>Wholesale price</span><strong>৳ {{ product.wholesalePrice.toLocaleString() }}</strong></div><div class="detail-row"><span>SKU</span><strong>{{ product.sku }}</strong></div><div class="detail-row"><span>Status</span><strong>{{ product.status }}</strong></div></div></section></div>
    <section class="card" style="margin-top:17px"><div class="card-header"><div><h2>Variants</h2><p>Child sellable units under this product</p></div><Link href="/inventory/variants/create" class="card-link">Add variant ↗</Link></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Variant</th><th>SKU</th><th>Barcode</th><th>Price</th><th>Stock</th></tr></thead><tbody><tr v-for="variant in variants" :key="variant.sku"><td class="data-title">{{ variant.name }}</td><td>{{ variant.sku }}</td><td>{{ variant.barcode || '—' }}</td><td>{{ variant.price }}</td><td>{{ variant.stock }}</td></tr><tr v-if="!variants.length"><td colspan="5" class="table-empty">No variants linked yet.</td></tr></tbody></table></div></section>
    <div class="danger-zone"><span>Archive this product when it should no longer be sold.</span><button class="btn btn-ghost btn-small" type="button" @click="archive(product.id)"><Trash2 :size="13" /> Archive</button></div>
</template>
